spring:
  application:
    name: location-service
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/location_db}
      auto-index-creation: true
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  cloud:
    config:
      enabled: false

server:
  port: ${SERVER_PORT:8082}
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    mongo:
      enabled: true
    redis:
      enabled: true

logging:
  level:
    com.fourkites.location: ${LOG_LEVEL:INFO}
    org.springframework.data.mongodb: ${MONGO_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

location:
  cleanup:
    stale-threshold-hours: 72
    archive-days: 30
  history:
    max-points-per-day: 1000
    compression-threshold: 500